### ISSUE TITLE
Max withs get removed partly

### ISSUE THREAD

**Issue by kaystrobach** [TYPO3-Documentation/sphinx_typo3_theme#102]
https://github.com/TYPO3-Documentation/sphinx_typo3_theme/blob/735b71510399fcf871f3eafba667e930205cac07/sass/_component_page.scss#L41

IS:

![grafik](https://user-images.githubusercontent.com/1185776/107930298-16da5500-6f7b-11eb-95f2-f2b3127c565f.png)

IS - with wider Page:

![grafik](https://user-images.githubusercontent.com/1185776/107930338-26f23480-6f7b-11eb-975b-23fdc6e62610.png)

Workaround:

```css
.page-main-inner {
    max-width: 1440px;
}
```

The maximum width should be set to ensure good readability.

**Comment by marble** [comment]
Resolved with v4.5.x
