### ISSUE TITLE
Sphinx Wagtail Theme

### ISSUE THREAD

**Issue by allcaps** [TYPO3-Documentation/sphinx_typo3_theme#104]
Hello,

I just wanted to let you know that we (Wagtail) forked this theme as a basis for our Sphinx Wagtail Theme.

https://pypi.org/project/sphinx-wagtail-theme/
https://github.com/wagtail/sphinx_wagtail_theme
https://wagtail.github.io/sphinx_wagtail_theme/

We are in the process of adjusting the theme. To make it our own. The theme will be used at https://docs.wagtail.io/en/stable/ and might be used by other (Wagtail) packages too.

Thank you for the great work and open sourcing your theme! 👍

**Comment by marble** [comment]
Good luck and success! Please keep us informed - we are open minded :-)
