### ISSUE TITLE
Make the drop shadow default for images

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#11]
If you use `:class: with-shadow ` (with `.. figure::` or `.. image::`), the image gets created with a drop shadow.

Lots of images in manuals do not do this. I think it should not be necessary to define this manually. I haven't seen a page with images in the documentation yet that would not have been improved with the drop shadow. 

See [Getting Started Tutorial](https://docs.typo3.org/typo3cms/GettingStartedTutorial/) and compare latest (with shadow) with [8.7](https://docs.typo3.org/typo3cms/GettingStartedTutorial/8.7/) version (without shadow).

Additionally, I would also propose to make the drop-shadow stronger (#98) and add an extra margin around images: TYPO3-Documentation/t3SphinxThemeRtd#104

**Comment by sypets** [comment]
Closing in favor of #83

**Comment by marble** [comment]
With the sphinx_typo3_theme images are shown "as is". This is the most reasonable default. Some predefined css classes are available and may be added: with-border, with-shadow. For illustration, this is what we have right now:
![158](https://user-images.githubusercontent.com/307057/100466639-81dd6380-30d1-11eb-900c-c9e9aeda2e33.png)
Let's keep the default this way.
