### ISSUE TITLE
The new button "How to edit" easily clicked by mistake instead of "Edit on GitHub"?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#122]
It already happened several times to me that I accidentally clicked on the "How to edit" instead of "Edit on GitHub". Does this happen to others too?

I think the original suggestions for adding this button suggested to just have a small "i" icon or have a link under the existing button. 

Disclaimer: I don't know what would be the best solution. I would like to just point out that it might be a problem or it might be possible to improve. 

![image](https://user-images.githubusercontent.com/13206455/114538374-9cb10e80-9c53-11eb-8f88-cdefc0dcf8a8.png)

**Comment by marble** [comment]
I'm planning to rearrange the buttons like this. Only the "Edit on …" button will be yellow:
![grafik](https://user-images.githubusercontent.com/307057/125791863-6cf83ae0-afce-453f-8d91-1cba5fcfd0c3.png)

Any objections?

**Comment by marble** [comment]
Solved by sphinx_typo3_theme v4.6.2 and Docker rendering container v2.9.0:
![grafik](https://user-images.githubusercontent.com/307057/126756088-ad29a2f1-c280-47fa-9b35-c4bc01702881.png)
