### ISSUE TITLE
Add a "report issue" or "report problem" button

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#13]
## Proposal 

Add a "Report problem" button (e.g. next to "Edit on GitHub") to make it even easier to report an issue for a particular page. 

This could automatically add the URL to the issue.

## Motivation

* "Issues" link in "Related Links" is somewhat hidden
* You need to scroll down and click twice to open an issue: click on "Issues", "Click on new"

## Advantages

* Even easier to report issues. 
* Adds context: Which URL
* Gives us the possibility to interact with new users early

## Disadvantages

* People might feel more inclined to report issues instead of editing. But this can be easily counteracted by suggesting a PR on a comment for an issue report or by providing templates that point out possibilities of creating PR.

## Implementation

Put a button on top of the page, e.g. next to "Edit me on GitHub". The link should directly point to create a new issue (Link to issue already in Settings.cfg, just add `/new` to it) (and add the current link to bodytext).

Example implementation:

https://our.umbraco.com/documentation/?_ga=2.186767979.293132607.1553321766-358997855.1553321766/

![report](https://user-images.githubusercontent.com/13206455/54862679-997e1980-4d3e-11e9-98e9-9c414b4848fe.png)

This writes the URL of the source file into the issue:

`***This is the page with issues: https://github.com/umbraco/UmbracoDocs/edit/master/index.md***`

## Related

In addition or alternatively, some of the other methods of giving feedback could be implemented as suggested in team issue ["Evaluate methods to get feedback (surveys, feedback button, ...)"](https://github.com/TYPO3-Documentation/T3DocTeam/issues/65).

**Comment by marble** [comment]
Nowadays each page has that button (if configured in the Settings.cfg):
![grafik](https://user-images.githubusercontent.com/307057/100465718-1fd02e80-30d0-11eb-9e09-2380651ac444.png)
In my opinion that is what the theme can do about it (without cluttering things up). Either people know what an issue is or they don't. So I considere this "done" with respect to the theme. Educating people is another topic.
