### ISSUE TITLE
4.6.0: Huge empty space on top

### ISSUE THREAD

**Issue by FlorianReimold** [TYPO3-Documentation/sphinx_typo3_theme#138]
I am using this theme for our [eCAL documentation](https://continental.github.io/ecal/). Currently I am on 5.5.2. After upgrading to 5.6.0 I am got a huge empty space between the header icon and the button row.

I guess this is caused by removing the body and footer from the page class (that has a min-height of 100vh) and leaving only the header inside:

With 4.5.2:
![typo3_4_5_2](https://user-images.githubusercontent.com/11774314/126286082-ed55a5f4-9f0f-49cc-af5a-3bfaea037d19.png)

With 4.6.0:
![typo3_4_6_0](https://user-images.githubusercontent.com/11774314/126286112-56f9f999-fc10-44b8-86b3-58ad3eea4db0.png)

I really like this theme and I am looking forward to a fix (I guess this will be easy for you). 😊

Regards
Florian

**Comment by marble** [comment]
Where can I see the "bad" display?

**Comment by FlorianReimold** [comment]
Didn't want to post that huge screenshot, but doing it anyways now ;-)

If it helps you I can locally upgrade the theme again and hand you the zipped htmls!

![ecal_doc_typo3_5_6_0](https://user-images.githubusercontent.com/11774314/126293269-29aafa7d-2b13-4d6e-a062-27188b2f3da0.png)

**Comment by marble** [comment]
Can we talk at https://typo3.slack.com ? Please get yourself an account and head over the the #typo3-documentation channel there, or ping me there directly. German preferred.

**Comment by FlorianReimold** [comment]
I tried to get an account, but there is only a form to log into an existing account with email and password. How do I get an account if I don't have one yet?

**Comment by marble** [comment]
It seems you have to login in to https://my.typo3.org. Get an account there, if you don't have one yet. Then click the "Open Slack" button 
![image](https://user-images.githubusercontent.com/307057/126330399-963e451e-28dd-4b99-9620-1df37d07ffb2.png)

**Comment by FlorianReimold** [comment]
Apparently somebody has to manually allow my registration.

In the meantime let me point out that you currently got the same issue with your own documentation 😉
https://typo3-documentation.github.io/sphinx_typo3_theme/

![typo3](https://user-images.githubusercontent.com/11774314/126335822-53bef2bd-f94a-4914-b7f3-05dad5a93cb7.png)

**Comment by marble** [comment]
Ok, thank you, that's the info I need (and I was afraid of). I'm on the brink of releasing a new theme and a new rendering Docker container, that's why it's very important to get this fixed. Thanks a lot for reporting.

**Comment by marble** [comment]
Bugfixed in layout.html
