### ISSUE TITLE
Change styling for shadow for images

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#14]
Design Team / Fabian Stein wants to change style for image shadow to make it consistent with Styleguide:

`box-shadow: 0 2px 4px 0 rgba(81, 81, 81, 0.2); `

**Comment by marble** [comment]
With the sphinx_typo3_theme images are shown "as is". This is the most reasonable default. Some predefined css classes are available and *may* be added: `with-border`, `with-shadow`. For illustration, this is what we have right now:
![grafik](https://user-images.githubusercontent.com/307057/100465071-f5ca3c80-30ce-11eb-9e16-186d6bc3e211.png)

**Comment by marble** [comment]
Resolved in #604eee1cff5bbb257899984497d4af3dca84196e
