### ISSUE TITLE
linenos with Sphinx 4.3

### ISSUE THREAD

**Issue by FlorianReimold** [TYPO3-Documentation/sphinx_typo3_theme#149]
When using Sphinx 4.3, `<span class="linenos">` and code lines are mixed up in the html code. When selecting text, this causes the lineos to be selected as well.

A code-block to reproduce is:

```
  .. literalinclude:: src/hello_world/hello_world_snd/CMakeLists.txt
     :language: cmake
     :linenos:
```

With Sphinx 4.3 linenos and code lines are mixed up, as can be seen in the inspector view in this screenshot:

![Screenshot from 2021-11-17 14-22-07](https://user-images.githubusercontent.com/11774314/142192143-f1b06c84-fe84-4aec-92d8-2eab660c0aa7.png)

With Sphinx 3.5.2 lineos and code lines were put into their own `<td class="linenos">` and `<td class="code">` containers and not mix up, so the code can be selected without also selecting line numbers:

![Screenshot from 2021-11-17 14-29-56](https://user-images.githubusercontent.com/11774314/142192619-1fdde15d-62fc-4123-b759-ed4f79b69e14.png)

Is this something that can be fixed from the theme?

**Comment by marble** [comment]
Hhm, thank you for the analysis. Just by reading what you write, I would say, it can't be done easily. One idea would be to tweak the copybutton and have JavaScript remove the linenums before copying. But I wouldn't like to take over the burden of having to maintain that. Let me have a look at the problem as well and maybe, with time there may appear a solution.

**Comment by FlorianReimold** [comment]
I did some more analysis and compared to the rtd theme. With rtd, linenos are not selectible:

![Screenshot from 2021-11-18 13-08-30](https://user-images.githubusercontent.com/11774314/142412829-d5a10c27-66bb-4490-9428-e8fbd4c22108.png)

I checked the css and found the following code:

```css
.rst-content div.highlight .gp, .rst-content div.highlight span.linenos {
    user-select: none;
    pointer-events: none
}
```
I think this is the solution.

**Comment by marble** [comment]
Oops, that sounds cool. I didn't know a css 'user-select' property existed. Will give that a try.

**Comment by marble** [comment]
Very good, good job, does what you found out:
![image](https://user-images.githubusercontent.com/307057/142431418-32f3a4df-d300-4423-a86c-ec33dbbeb48b.png)

- https://github.com/TYPO3-Documentation/sphinx_typo3_theme/commit/b1d0f885e5077a3d888360eb7e64fa11fc81148d
- https://github.com/TYPO3-Documentation/sphinx_typo3_theme/commit/d614583f974fcabac89a4607e50030418878b370
- Can (later...) be seen here: https://typo3-documentation.github.io/sphinx_typo3_theme_rendering_test/Codeblocks/Index.html

Thank you for your help.
