### ISSUE TITLE
Use italic font variants

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/sphinx_typo3_theme#155]
The italic letters rendered with the TYPO3 Sphinx theme don't look ideal, they look too diagonal. This could probably be optimized by including and using the italic variant of the original fonts instead of relying on the browser's italic rendering - as is done already with the bold rendering. The [Source Sans Pro](https://adobe-fonts.github.io/source-sans/) and [Source Code Pro](http://adobe-fonts.github.io/source-code-pro/) fonts both have italic variants that could be downloaded and added to the [/sass/webfonts.scss](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/blob/master/sass/webfonts.scss) theme file. What do you think about this?

**Comment by marble** [comment]
Why not. ((when already - then already // Wenn schon, denn schon! :-))

**Comment by marble** [comment]
## Taking notes while working

How to use these?
- https://fontsource.org/fonts/source-sans-pro
- `yarn add @fontsource/source-sans-pro`
- https://fontsource.org/fonts/source-code-pro
- `yarn add @fontsource/source-code-pro`

Is it ok to only use WOFF files?

Currently and up to now we have been using eot, svg, ttf, woff, woff2.
<pre>
/* source-code-pro-regular - latin */
@font-face {
    font-family: 'Source Code Pro';
    font-style: normal;
    font-weight: 400;
    src: url('../fonts/source-code-pro-v11-latin-regular.eot');
    src:
        local('Source Code Pro Regular'),
        local('SourceCodePro-Regular'),
        url('../fonts/source-code-pro-v11-latin-regular.eot?#iefix') format('embedded-opentype'),
        url('../fonts/source-code-pro-v11-latin-regular.woff2') format('woff2'),
        url('../fonts/source-code-pro-v11-latin-regular.woff') format('woff'),
        url('../fonts/source-code-pro-v11-latin-regular.ttf') format('truetype'),
        url('../fonts/source-code-pro-v11-latin-regular.svg#SourceCodePro') format('svg');
}
</pre>

**Comment by marble** [comment]
Done with https://github.com/TYPO3-Documentation/sphinx_typo3_theme/commit/6be76ccdbe76be6c7159d1b203311479f22bf3aa
and Docker Rendering Container 'develop = v3.0.dev14'
