### ISSUE TITLE
similar option like 'sticky_navigation' in sphinx_rtd_theme

### ISSUE THREAD

**Issue by zhqrbitee** [TYPO3-Documentation/sphinx_typo3_theme#156]
Hi, 
Do we have a 'sticky_navigation' option like: https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-sticky_navigation?  
Basically I want the navigation bar scroll with the main page, since I have a very long main page and it is painful to scroll back to see the navigation bar.

**Comment by marble** [comment]
Sorry, I'm afraid we don't have that at the moment. But I think it's a valid request and desirable feature. So I leave this ticket open and will try in future to find out if and how this feature can be added.

**Comment by sypets** [comment]
I think this would be very useful for our docs. We have quite long pages and if the menu is scrolled away, it is not possible to see the structure. Also, the structure on the page is a bit hidden under "Page content" which must be clicked open to see it.

Compare clicking through the sections using the navigation on the left on these 2 pages:

* readthedocs: https://docs.phpunit.de/en/10.1/test-doubles.html#returnvaluemap
* TYPO3 docs: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/FlexForms/Index.html

As soon as the reader clicks to jump to a different section on the TYPO3 page, the page scrolls and the navigation is no longer visible.

It is not only helpful, to be able to use the menu to jump to another page, but also to jump to a different section on the current page. (Ideally, the reader does not even have to worry about whether it is one or the other).

**Comment by marble** [comment]
Closed for now.
