### ISSUE TITLE
Add css highlighting for `:css:` text role

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/sphinx_typo3_theme#160]
The /sass/_component_rst.scss file contains all supported css classes of supported reST text roles, for example
```
code {
    &.file {
        color: $code-color-file;
    }
    &.html {
        color: $code-color-html;
    }
    ..
}
```
What seems to be missing is a class for css, which could be used in a text role `:css:`. Such text role is already semantically used in EXT:core documentation but missing the styling.

**Comment by marble** [comment]
Done with 4.6.3.dev60+gc7d5ec0
