### ISSUE TITLE
Add additional help to search results page

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#17]
# Problems

The [search result page](https://docs.typo3.org/typo3cms/HowToDocument/search.html?q=sdfsf&check_keywords=yes&area=default#) currently contains this text for no result:

```
Search Results
Your search did not match any documents. Please make sure that all words 
are spelled correctly and that you've selected enough categories.
```

* it is not possible to select categories so this is misleading

Also, whether results are displayed or not:

 * Users should be made aware that only the current manual is searched
 * There is no additional link for searching entire docs

# Possible solutions

* remove part about categories
* Search results page should always display additional information or a link to additional information at the top (whether results are found or not), e.g. 

```
Did not find what you are looking for? 

The search box on the left currently only searches within the 
current manual (<insert title of manual here>). 

Use <insert link to startpage.com with search query> to 
search through entire TYPO3 documentation. 
```

**Comment by sypets** [comment]
Very old issue. No high priority.

**Comment by alexander-nitsche** [comment]
This is still valid and a good proposal. Want to add that there should be always a link to the global search prefilled with the current search term. The comments in the result pages could be something like:

**(1) No results**

Status Quo:
```
Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories.
```
Proposal:
```
Your search for "<query>" did not match any pages in this "<documentation-title>" documentation. Click `here <https://docs.typo3.org/search/search?q=<query>>`__ to search the entire TYPO3 documentation instead. 
```

**(2) With results**

Status Quo:
```
Search finished, found 4 page(s) matching the search query.
```
Proposal:
```
Search for "<query>" in this "<documentation-title>" documentation finished, 4 page(s) found. Click `here <https://docs.typo3.org/search/search?q=<query>>`__ to search the entire TYPO3 documentation instead. 
```
