### ISSUE TITLE
Styling of confval directive

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/sphinx_typo3_theme#170]
With the new theme the confval directive gets rendered like this:

![NewsConfval](https://user-images.githubusercontent.com/48202465/178826128-186e3cae-f77b-4781-8714-329d3df5382a.png)

While I like the new form and tab-like apppearance there are some drawbacks:

The red text on the brownish background is not accessible enough: https://contrast-ratio.com/#%23c02-on-%23ECDCC6, it only has a contrast ratio of 4.35.

The background color is not used in other places. The red of the text feels like a warning and doesn't really go along with our TYPO3 orange.

Also as we are talking about configuration values I would like to keep the code-like monospaced font. I would suggest to style the confvals like this:

![Idee1](https://user-images.githubusercontent.com/48202465/178826680-e4019f0d-77e9-4c1b-a97a-2d2295b17794.png)

The text of the confval theme would have a contrast of over 18 then and is easy to read: https://contrast-ratio.com/#%23000-on-%23e8e8e8 and the colors appear elsewhere on the site.

Before the update the confval looked like this:

![image](https://user-images.githubusercontent.com/48202465/178826970-3f46caa0-5e5f-4f8c-89bb-e9d6892e8700.png)

The contrast ratio of 2,83 https://contrast-ratio.com/#%23ff5370-on-%23EBF7FB was even worse for the color blind and we had the problem of colours that appear nowhere else.

If you agree, Martin I can provide a PR for this.

**Comment by marble** [comment]
Fixed in sphinx_typo3_theme >=4.7.6.dev3+gb8ca847, scheduled for DRC >= v3.0.dev27
