### ISSUE TITLE
Link to go back to start page is missing

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#171]
https://docs.typo3.org/p/ttn/tea/main/en-us/#typo3-documentation

![image](https://user-images.githubusercontent.com/13206455/178939012-b1309e78-9dee-4a17-8172-114033a6feba.png)

There used to be a link there which pointed to the start page

**Comment by marble** [comment]
Fixed with >= sphinx_typo3_theme-4.7.6.dev2+g49fe962 for DRC >= v3.0.dev27
