### ISSUE TITLE
Text is white/gray

### ISSUE THREAD

**Issue by paul-shuvo** [TYPO3-Documentation/sphinx_typo3_theme#174]
I'm getting the following output. Most of the text is like this. 

![image](https://user-images.githubusercontent.com/2852539/186854470-1160dcb0-0d26-4195-bfd6-d195cb0c4ae0.png)

**Comment by marble** [comment]
Please provide a link to the problematic page. In which browser(s)?

**Comment by paul-shuvo** [comment]
I'm developing locally. I've tried with Firefox, Chrome, and Opera; same result. The code is [here](https://github.com/paul-shuvo/gazetimation/tree/dev)

**Comment by marble** [comment]
I see. Will have a look at it next week.

**Comment by marble** [comment]
Hello paul-shuvo,

1. please try again and restrict Sphinx like so: `sphinx>=4.5.0,<5.0`. We haven't been using the sphinx_typo3_theme with Sphinx v5.x yet.
2. Does it help?
3. What a cool and interesting project is that. I have it running on my machine as well, only had to change the video device to 4.
4. When I try to just render the documentation with `make html` or `sphinx-build source build` the program is being started. Why and how? Can I turn that off? It gets in the way of rendering, and I need ctrl+c to stop the camera processing (But that is working!!!). Can't I just render the docs? I'd like to test our theme. We haven't been using it actually for documenting Python code, so I'm interested.

**Comment by paul-shuvo** [comment]
Hi marble,

1. I tried with `sphinx==4.5.0` and still it doesn't render properly. I have attached a screenshot below.
![image](https://user-images.githubusercontent.com/2852539/187241866-94f13ea4-ddda-458d-a554-6fa7ce70fc10.png)
2. You can check this [commit](https://github.com/paul-shuvo/gazetimation/commit/2181239f99bd21949281ec944308cf4e611be022).
3. Thank you :smiley:. I'm glad you liked it.
4.  I accidentally had it running in one of the src files. It should fine now.

Thanks again for your help!

**Comment by marble** [comment]
Thank you very much on your input. I can exactly reproduce the error. It is enlightening for me to see your docs code.
Our theme simply hadn't been used so far in this way so we weren't aware of the problem. I'll work on a fix soon and let you know about it.

**Comment by paul-shuvo** [comment]
Thanks a lot for your help!

**Comment by marble** [comment]
I just released v4.7.7 of sphinx_typo3_theme. IMHO and according to my tests it does work. I refactored the highlighting stuff, and that also addressed the bug with the `.py` class. Note however, that the theme doesn't contain yet fancy styles for the syntax-highlighting classes that `sphinx.ext.autodoc` inserts. I'm simply not aware of some kind of total listing of what classes are used. If you know something about this, please let me know. `codeblocks.(s)css` now is a standalone file and can be used to experiment with extra rules. Nevertheless, IMHO it's looking rather nice already:
![image](https://user-images.githubusercontent.com/307057/188491229-87dbea3f-69d6-4a1e-9982-09977699b3b0.png)
