### ISSUE TITLE
Clamp multiple paragraphs of directives like "versionadded" visually

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/sphinx_typo3_theme#177]
We use the directives "versionadded", "versionchanged" and "deprecated" quite often in the docs - often also with mulitple paragraphos or in combination with a list. Sometimes it is not clear where the directive ends and a "normal" paragraph starts:

![image](https://user-images.githubusercontent.com/2566282/200131645-a088e3cb-655d-4043-b377-c754c8063cfd.png)

One solution might be to add a left border to clamp them:

![image](https://user-images.githubusercontent.com/2566282/200131679-e720a6b6-0030-4742-b884-8cd39be83b78.png)

Another solution might be to set a background colour:

![image](https://user-images.githubusercontent.com/2566282/200131710-5f92b82b-4fed-4bb4-921d-084e8a9e493c.png)

Personally, I like the left border more because the background color is used by admonitions and sometimes admontition and those version directives follow in the text.

Also a single directive without additional text should be considered:

![image](https://user-images.githubusercontent.com/2566282/200131902-ae720481-227d-4cde-a0ab-5a8dbcc2ed4a.png)

**Comment by sypets** [comment]
> Sometimes it is not clear where the directive ends and a "normal" paragraph starts:

I agree. I think it is a good idea to generally have it in some kind of a box visually separated, whether that is a frame or with a border on the left side, I don't care much as long as it is obvious.

**Comment by marble** [comment]
To deal with that issue: Can you come up with a list of links to usecase which you would consider 'sub-optimal'? Then we can check whether this is best be solved by writing the RST source differently or by tweaking the theme.

**Comment by brotkrueml** [comment]
This one for example:
https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/Configuration/ConfigurationFiles.html?highlight=localconfiguration#migration

It is not clear where the "changed" ends.

**Comment by brotkrueml** [comment]
Also for this PR with a mix of different hints:
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/3157/files
It is hard to grasp where they real text starts and what are just annotations.

**Comment by brotkrueml** [comment]
Another example: Where ends the new note and starts the real text?
https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Events/Events/Frontend/AfterCacheableContentIsGeneratedEvent.html

**Comment by marble** [comment]
In an extreme demo case this looks like:
![image](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/assets/307057/ffd1fbc5-feb7-4d73-ba9b-e36491c25285)

Not bad, I'd say.

**Comment by brotkrueml** [comment]
Fine for me, it has now a clear separation to the surrounding text.

@linawolf What do you think?

**Comment by marble** [comment]
Done with https://github.com/TYPO3-Documentation/sphinx_typo3_theme/commit/9f72698869b36dddf0ff15830c6bb5fba99d99de
