### ISSUE TITLE
Improve the version switcher - "unhide" it

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/sphinx_typo3_theme#18]
1. Idea: Add 'hover' behaviour: Links have the hover effeckt
![grafik](https://user-images.githubusercontent.com/307057/42331928-04673a78-8077-11e8-8bd9-494ad1486fb6.png)

Let the version switcher have that as well:
![grafik](https://user-images.githubusercontent.com/307057/42332107-79723c14-8077-11e8-8ded-5de72d702c4a.png)

**Comment by sypets** [comment]
I think we can close this now. Please reopen, if you think this is the wrong decision.
