### ISSUE TITLE
`t3-function-*` are not recognizable as links

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/sphinx_typo3_theme#181]
Using the `t3-function-*` directive also renders a link, for example:

![image](https://user-images.githubusercontent.com/2566282/207101006-bdf93555-0633-4858-a6f7-7cc2bccdc71e.png)

The `pidInList` is such a link, from source:

```rst
:t3-function-select:`pidInList` defaults to :typoscript:`this`.
```

The docs page: https://docs.typo3.org/m/typo3/reference-typoscript/11.5/en-us/Functions/Select.html#uidinlist

That visual representation has two disadvantages:

- This link is not visible as a link. An average reader of the docs doesn't know their can click on it. As a link is mostly known to be underlined, we should change this.
- The contrast is horrible: A light orange on light grey is bad to read (at least for me and I think also for others). When we want to be inclusive and accessible (which I assume), the contrast must be enhanced.

So, I suggest to remove the grey background, the border and just render it as a normal link.

**Comment by DavidBruchmann** [comment]
Actually the orange is hard to read also on white background.  
I think it should be at least darker--if still orange--or perhaps better black or grey.
I fear though this might be a hard discussion, where I don't even know where it could be happen and decided.

**Comment by brotkrueml** [comment]
Yup, the docs are hard to read for visually impaired people (contrast is too low for some parts, like links). So we should decide if we want to include or exclude those people.

**Comment by sypets** [comment]
> Yup, the docs are hard to read for visually impaired people (contrast is too low for some parts, like links). So we should decide if we want to include or exclude those people.

Having an [accessibility team](https://typo3.org/community/teams/accessibility) and tons of patches for accessibility in the core - I think this is a strong indicator the same principles should be applied in the docs as well. 

What is the intention of ` :t3-function-select:`? 

About  marking code as inline code - IMHO it would be good if we can find a best practice which does not result in as many (different) markups on the pages and as many markups in general  (This is in addition to the contrast issue).

When I contribute, there are usually review suggestions to add more  inline markup, not less. I don't always agree with the way it is currently done.

I find this is (on some pages) overused and it visually clutters the pages (as well as the admonitions) - apart from the accessibility and contrast. (But the impact can be controlled a little by how it is styled).

These issues are all related: the way markup is styled (theme issue), when and how often markup is used (edit issue). 

This concerns the inline code, also the versionadded etc. and the admonitions.

Related: #176

**Comment by marble** [comment]
Is this ticket still of interest?

- if so, where?
- It seems, the above link doesn't show the problem any more.
- Note that inline code is about to be visualized with less "visual noise" https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/176

**Comment by brotkrueml** [comment]
Here for example: https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/Functions/Stdwrap.html#addpagecachetags

"string" in "Data type" is not recognisable as a link, also "cache" in the note. Apart from it is badly readable because of the colour (at least for my eyes).

**Comment by brotkrueml** [comment]
Here a different approch: 
https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/Functions/Stdwrap.html#field

`$cObj->data[*field*]` has also a sourringing box, but is not link (but an inline code snippet).

Okay, the example from above (string | cache) is orange (like the links). but it has also a sorrounding box. For me it is not clear that orange with a surrounding box is a link. The content in the surrounding box (code snippets) have different colours dependent on the language the represent. We should clearly mark links as link, so that they are obvious.

But maybe this is a bigger task.

**Comment by marble** [comment]
> Here for example: https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/Functions/Stdwrap.html#addpagecachetags
> 
> "string" in "Data type" is not recognisable as a link, also "cache" in the note. Apart from it is badly readable because of the colour (at least for my eyes).

In reaction to #176 visual noise is already reduced, so it will become:
![grafik](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/assets/307057/953c1606-eada-44a3-8c8d-5039643859b0)

Which isn't bad, I would say. The TYPO3 orange as link color is bad, of course.

Lets see how it works out, once the next theme and container version is deployed. Until then I close the ticket and assign label "closed for now".
