### ISSUE TITLE
Increase the size of contents in body of index

### ISSUE THREAD

**Issue by Tuxman2** [TYPO3-Documentation/sphinx_typo3_theme#208]
Hello,

![typo3](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/assets/23556606/515a733f-7fe1-4988-b242-e634c6b8916d)

is there a way to increase this text ? I think it can be do in theme.css file but I don't know where.

Thanks.

Regards.

Note: it depends of :caption: in toctree

**Comment by marble** [comment]
Should be easy to improve. I'll take a look. The only question is: What size would be best?

**Comment by Tuxman2** [comment]
This size ?


![Size](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/assets/23556606/e2f4f022-c793-4503-a86d-6c65448de44f)

**Comment by marble** [comment]
Done in upcoming release. I've given it the size of H3.
![grafik](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/assets/307057/2f0cc0e6-9b4c-42f1-9472-177a0cc810ea)
