### ISSUE TITLE
Provide a possibility for downloadable snippets / copy to clipboard

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#22]
see 

- https://www.dokuwiki.org/wiki:syntax#downloadable_code_blocks
- https://typo3.slack.com/archives/C028JEPJL/p1518785609000381

![grafik](https://user-images.githubusercontent.com/307057/42165418-3a48b69c-7e08-11e8-90ea-2364ddc065b2.png)

**Comment by marble** [comment]
https://www.30secondsofcode.org/js/s/copy-to-clipboard
![grafik](https://user-images.githubusercontent.com/307057/95560333-6df27b00-0a19-11eb-8dc0-00ec335b7837.png)

**Comment by susannemoog** [comment]
How about using https://sphinx-copybutton.readthedocs.io/en/latest/ ?

**Comment by marble** [comment]
> How about using https://sphinx-copybutton.readthedocs.io/en/latest/ ?

Cool, will have a look.

**Comment by marble** [comment]
Done and solved with Docker rendering container version v2.9.0
