### ISSUE TITLE
Improve styling of blockquotes

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/sphinx_typo3_theme#24]
# Example

https://typo3.com/blog/recap-typo3-camp-mitteldeutschland-2018-t3cmd/?utm_medium=twitter&utm_source=dlvr.it&utm_campaign=Blog%3A%2BEvent%2BRecap

<pre>
blockquote:before {
        color: #b3b3b3;
        content: "\f10e";
        font-size: 1.5em;
        font-family: 'Font Awesome 5 Pro';
        line-height: 1em;
        margin-right: .5em;
        vertical-align: -.2em;
}
</pre>
![446](https://user-images.githubusercontent.com/307057/35725816-f87cb306-0802-11e8-9043-c6ee5ac11440.png)

See symbol https://fontawesome.com/icons/quote-right?style=solid

Consider: https://1stwebdesigner.com/css-snippets-blockquotes/

**Comment by benjaminkott** [comment]
Resolved with https://github.com/TYPO3-Documentation/sphinx_typo3_theme/commit/0793f6ae1c171df3cc0dd1dcc2d13089a2afecf6
