### ISSUE TITLE
Document how uploading to pypi.org works

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/sphinx_typo3_theme#26]
The procedure to upload packages used to be like depicted here: http://mbless.de/blog/2015/06/16/a-new-theme-for-docs-typo3-org.html?highlight=pypi#knowhow-for-the-pypi-package-maintainer

Now pypi has move to pypi.org and has a new Webinterface. The old API doesn't work (atm).

A form-based upload on the webpages does work.

ToDo: Write documentation how it works.

**Comment by benjaminkott** [comment]
Documented in Workflow file and executed on release creation. 
https://github.com/TYPO3-Documentation/sphinx_typo3_theme/blob/master/.github/workflows/python-publish.yml
