### ISSUE TITLE
Information about LTS, ELTS (e.g. show status for version of page you are currently reading)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#31]
Symfony adds information about maintained / unmaintained versions in their version selector.

![symfony](https://user-images.githubusercontent.com/13206455/73125010-59ad4180-3fa2-11ea-94c8-402adf4d89b0.png)

example: https://symfony.com/doc/current/console.html

They also differentiate between the latest release (current) and master. 

An alternative might be to show the ELTS / LTS status along with the version.

For us, it would look like this:

* latest: main (e.g. 12-dev)
* LTS: 11.5., 10.4
* ELTS: 9.5 etc.

**Comment by sypets** [comment]
I also made a suggestion to separate "latest" (latest release) and "master" (unreleased version, identical with core master): https://github.com/TYPO3-Documentation/T3DocTeam/issues/133

If this change is made, it might be a good idea to consider that other change as well.

**Comment by sypets** [comment]
Low priority, closing to declutter issues.

**Comment by alexander-nitsche** [comment]
This topic is discussed currently in the marketing slack channel, closely related to the recently introduced [TYPO3 documentation icon set](https://github.com/TYPO3-Documentation/Assets-T3-Icons-1). I post in here the current state of the discussion: The idea is to use an icon as indicator of LTS / ELTS / No Support of the current documentation version.

---

**Alexander Nitsche  2 months ago**
hi marketing team,

dropping the idea here for the designers of the new icon set: would be nice to have a unique icon for each TYPO3 LTS release whose overall appearance clearly differs from the ones of other releases (in color and maybe also in shape) and to have that icon in three variants:

Variant 1: This TYPO3 release is supported by LTS
Variant 2: This TYPO3 release is supported by ELTS only
Variant 3: This TYPO3 release is not supported anymore

and for two publishing channels:

Large scale: Symbol with many details for being displayed large scaled, e.g. on documentation pages, presentation slides, etc.
Small scale: Symbol with very few details for being displayed small scaled, e.g. in badges in README files.

one use case would be to place it somewhere in the content or frame of the TYPO3 documentation manuals, and having it linked to an appropriate central page that explains all three modes and advises the reader on the next steps. other use cases would be branding branding branding :slightly_smiling_face: (edited) 

**Markus Schwarz  1 month ago**
Well, yes, sounds like a good idea. I just wouldn't make the icons stand out too much from each other, it should be consistent somewhere. Maybe the version number should be integrated to differentiate. Can think about it when I find the time.

**Alexander Nitsche  1 month ago**
distinguishing the icons just by the release number would probably fail to serve the purpose to immediately make the user aware of the typo3 context s:he is currently in. especially for the small scaled icons.

**Fabian Stein  1 month ago**
Hi Guys, sorry i was on vacation the last time. I like the idea very much as well. @alexandernitsche do you have access to the Jira? Maybe we could make some tickets out of it to clearify the specific requirements?

**Alexander Nitsche  1 month ago**
hi fabian, no, i have no access to jira. not sure what the best approach is as markus also wanted to make up his mind on it ..

**Markus Schwarz  1 month ago**
@fabianstein let's stick to the process, that's best I think (making jira tickets and discuss the request in the team meeting)

**Luisa Faßbender  1 month ago**
Sorry for my late reply, but I’m honestly not really sure about this. Are you talking about 3 different logo variations for each LTS release or three variants in general?

**Alexander Nitsche  29 days ago**
let's stick to the process, that's best I think (making jira tickets and discuss the request in the team meeting)
ok, who will create those tickets? should i ask for jira access?

**Alexander Nitsche  22 days ago**
hi guys, how to proceed here? is anything to be prepared for your next team meeting?

**Markus Schwarz  20 days ago**
Hey Alexander, I think we'll discuss this in our next designteam meeting, no need for preparing anything. We will decide then how to proceed and get back to you, right @fabianstein? (edited)

**Comment by marble** [comment]
The main problem whith this topic is that there needs to be some kind of "authority" (people, convention, database, mandatory list) that defines which manual should have which banner. Could be included via server side includes, for example.

To make provisions in the theme comes second.

However, there is an easy "hack" which has been tried and works very well: Add an infobox in `Includes.rst.txt`. To our surprise this has turned out to work very well. Example:

See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/10.4/Documentation/Includes.rst.txt?plain=1

![grafik](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/assets/307057/a3540eb5-a50e-48be-9f5b-7bf89ef108af)

Now each page starts with this 'attention' message:
![grafik](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/assets/307057/9ac0902c-ec73-4c75-a6c2-4926eced9cb8)

On the pro side is, that it's up to the editors to add that note.
The downside is, that it will probably be used inconsistently.

I'll close the issue (for now) (again).

**Comment by sypets** [comment]
I think the way it is now is already quite good. The banner about ELTS etc. is displayed for some time now.
