### ISSUE TITLE
Search results page: snippet generation: beginning of HTML source is shown instead of snippets

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#44]
```
<!DOCTYPE html> <!--[if IE 8]><html class="no-js lt-ie9" lang="en" > <![endif]--><!--[if gt IE 8]><!--><html class="no-js" lang="en"> <!--<![endif]--> <head> <meta charset="utf-8"/> <base href="https://docs.typo3.org/"> <meta content="width...
```

![search](https://user-images.githubusercontent.com/13206455/73353329-662be580-4293-11ea-87d0-4db088281896.png)

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/search.html?q=dependency+injection&check_keywords=yes&area=default

**Comment by sypets** [comment]
I noticed this in current version of the theme, I did not test yet with new version.

**Comment by marble** [comment]
Obsolete. Fixed with the new sphinx_typo3_theme.
