### ISSUE TITLE
Quick fix: Add a link to global search engine?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#46]
This is a **quick fix** for current search problem. It is not intended as a permanent solution. Maybe this initial idea can be improved?

It does not look like we will get the global search solution as originally planned any time soon. Current search has several problems. See [other issues with label search](https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+search%22) and also the problem that search only searches in _current_ manual.

I think for most users, using an external search engine would be best for now. If we add a link, we give a hint that there are alternatives and make it easier for people to just click. 

![search4](https://user-images.githubusercontent.com/13206455/73356730-48fb1500-429b-11ea-84fe-d2f8323a219a.png)

Even better would be if the current search term was added automatically to the external link (which could be done via JavaScript). 

**This is really just a simple link. It is no integration of the external search engine whatsoever!**

----

Links for external search engines (I am using google here, but the links should work with most other search engines like start page or duckduckgo):

**all docs:**

`site:docs.typo3.org`
https://www.google.com/search?q=site%3Adocs.typo3.org&oq=site%3Adocs.typo3.org

**In specific manual**
Example for "TYPO3 Explained"
`site:docs.typo3.org "/typo3/reference-coreapi/"`

https://www.google.com/search?q=site%3Adocs.typo3.org+%22typo3%2Freference-coreapi%22

Example with search term "dependency injection"
`site:docs.typo3.org "typo3/reference-coreapi" dependency injection`

https://www.google.com/search?q=site%3Adocs.typo3.org+%22typo3%2Freference-coreapi%22+dependency+injection

---------

Related:

* I already suggested to add a link to an external search engine in #17

**Comment by marble** [comment]
The global search form is now part of all pages. Theme v4.6.2, container v2.9.0
