### ISSUE TITLE
Problem with tables (truncated, horizontal scrollbar)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#47]
[Slack](https://typo3.slack.com/archives/C028JEPJL/p1580832359153300): 

> hi, I just stumbled upon a rendering issue: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.html
All the text in the table is truncated on the right side, can you see that? Is there anything that can be done?

> It's caused by the exceptionalErrors row, the <p> tag  with the constants consumes more space than available.

```
code, .rst-content tt, .rst-content code {
    white-space: nowrap;
}

```
This CSS breaks it

----

**Related:**

* ["Rethink use of tables in some places"](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/644) (TYPO3 Explained)

**Comment by marble** [comment]
I just looked at the mentioned example page. It looks ok to me. Yes, you need to do horizontal scrolling with some tables or code-blocks. But everything seems to be shown in the best way you can do.
Starting with theme version v4.3 and container v2.7 this will be less of a problem, as with a browser window that is >= 2.800px all of the width will be used and most, if not all of the content should be visible.
