### ISSUE TITLE
Add styles for version hints (versionadded, versionchanged etc.)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#5]
We would like to add version hints to the docs to point out "changed since", "deprecated since", etc. https://github.com/TYPO3-Documentation/T3DocTeam/issues/14#issuecomment-575978514

sphinx: http://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

This is currently not styled differently, it is just styled as normal text.

-------
reST:

```
.. versionadded:: 10.2
	PSR-14 events replace hooks and signals.

.. versionchanged:: 2.3.1
	This feature was changed

.. deprecated:: 10.3
	Use ... instead of SwitchableControllerActions
```

----

HTML

```
<div class="versionadded">
<p><span class="versionmodified">New in version 1.0.0: </span>This feature was added</p>
</div>
```

How it looks:

![picture](https://user-images.githubusercontent.com/13206455/72677469-13854900-3a9d-11ea-85df-e50699ef949f.png)

**Comment by sypets** [comment]
The "New in version xyz", "Change in version xyz" etc. currently looks like it uses italics. 

My wish would be to have this easily noticable and recognizable when scanning / scrolling / quickly glancing over a page but not too flashy that it distracts from reading. So it should maybe use a style that is not used for other things.

I think current style is ok, but might be improved.

**Comment by sypets** [comment]
Example page: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/CommandControllers/Index.html

**Comment by marble** [comment]
Upcoming theme v4.3 (container v2.7) will - hopefully - solve this with something like this:
![grafik](https://user-images.githubusercontent.com/307057/100471776-45af0080-30db-11eb-8fb2-ee43600b2414.png)
