### ISSUE TITLE
Drop arrows

### ISSUE THREAD

**Issue by mbrodala** [TYPO3-Documentation/sphinx_typo3_theme#58]
It has been bugging me for a while and now I'd like to discuss it: I don't see a point in the arrows used in the navigation:

![image](https://user-images.githubusercontent.com/5037116/75348028-590a1280-58a2-11ea-83d0-41b7b6264dbc.png)

The arrows create unnecessary visual noise and have no apparent purpose. Thus I'd like to suggest to drop them, at least from the navigation.

**Comment by sypets** [comment]
@mbrodala These are inserted in the .rst source. We could remove them in the Docs homepage: https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/blob/master/Documentation/Index.rst 

No theme change necessary. 

I think, it was originally intended to differentiate between items in the menu of one manual (that are pulled in via toctree) - in this case of the docs homepage - and links to other manuals.

In practice, from the point of view of the end user, this is probably not helpful (or at least not intuitive). It would be ideal, if the documentation presented itself as one homogenous website. 

Here we - again - have something that might be easier to handle if all documentation were in **one** repo and in **one** main manual. However, as discussed, this has some drawback like time for rendering etc.

**Comment by marble** [comment]
+1 For removing the arrows.

**Comment by benjaminkott** [comment]
Arrows removed.

**Comment by mbrodala** [comment]
Thanks, looks so much cleaner now. :-)

![image](https://user-images.githubusercontent.com/5037116/75422918-e9e1fc00-593d-11ea-85e0-45a0e24ccb2a.png)
