### ISSUE TITLE
Issues with highlighting of search term on page with ?highlight=

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#6]
Was raised on [Slack](https://typo3.slack.com/archives/C028JEPJL/p1578648884044900):

`?highlight=<search terms>` gets added to URL that are linked on search result page.

Example:
1) search f. `dependency injection` in TYPO3 Explained
2) click result, e.g. https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/DependencyInjection/Index.html?highlight=dependency%20injection

Issues:
* highlighting very obtrusive
* highlighting adds extra spaces, these causes problems when copying code snippet

Feature request:

* button to turn off highlighting
* make hightlighting less flashy or less orange, e.g. see results on other pages.

**Comment by marble** [comment]
Solved since theme v4.2 (container v2.6):
![grafik](https://user-images.githubusercontent.com/307057/100471425-8bb79480-30da-11eb-98c2-346c7dade057.png)
