### ISSUE TITLE
Possibly add style for version hints

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#61]
We use directives `deprecated`, `versionadded` etc. Should this get a style (e.g. with indent, slightly different color, border ...?) to make it more easily visible when skimming text?
 
Is documented here: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/HowToUpdateDocs.html#how-to-add-version-hints

This is an example page: 
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Mail/Index.html

```
<div class="versionadded">
<p><span class="versionmodified">New in version 10.0: </span>Symfony mailer and mime support was added with this change:
<a class="reference external" href="https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88643-NewMailAPIBasedOnSymfonymailerAndSymfonymime.html" title="(in TYPO3 CMS Core ChangeLog vlatest (10-dev))"><span>Feature: #88643 - New Mail API based on symfony/mailer and symfony/mime</span></a></p>
</div>
```

**Comment by sypets** [comment]
After looking at some examples I wish for a visible divider between the main text and what the version hint describes (e.g. by using border, indenting, different colors). Even in the Salt and Flask example below, you might not see right away, what is the main text and what does the change describe. 

Examples: Here are some examples form other documentation projects:

---------

![snippet](https://user-images.githubusercontent.com/13206455/75699833-631c7e80-5cb1-11ea-9fd6-ac721f20e182.png)
https://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules

Not a huge fan of the green, but it stands out

---
flask has made this clickable. I'm not a huge fan of having to click too much, but for inspiration ...

![snippet2](https://user-images.githubusercontent.com/13206455/75700007-b55d9f80-5cb1-11ea-83cc-263ac832602e.png)


https://flask.palletsprojects.com/en/1.1.x/config/

**Comment by marble** [comment]
For Docker container v2.7, going for:
![image](https://user-images.githubusercontent.com/307057/100120711-907d0e00-2e78-11eb-93a1-da6516623d6b.png)

![image](https://user-images.githubusercontent.com/307057/100120787-a38fde00-2e78-11eb-8ab2-7251d6ceeaa2.png)
