### ISSUE TITLE
Add links for 3rd level headers

### ISSUE THREAD

**Issue by mbrodala** [TYPO3-Documentation/sphinx_typo3_theme#62]
On docs.typo3.org there are currently 2 levels of headers linked in the navigation, e.g. in the [TypoScript reference](https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Functions/Stdwrap.html):

![image](https://user-images.githubusercontent.com/5037116/76609502-c6ab7500-6517-11ea-9e00-054b09693047.png)

All header levels beyond that are not linked anmyore and thus not accessible via links like the previous theme:

![image](https://user-images.githubusercontent.com/5037116/76609308-78967180-6517-11ea-92ed-790e35bf542f.png)

Here something needs to be integrated to add links at least for the 3rd level headers, if necessary even further. Putting all of this in the main navigation will probably be too much so maybe an autogenerated table of contents (TOC) on each page could help.

**Comment by dogawaf** [comment]
I use the documentation references on a daily basis: typoscript reference, tsconfig reference, TCA reference.
I really miss this 3rd level of navigation, which was a fast way to find an option among the huge list of options.

**Comment by sypets** [comment]
Here is another example, where the new menu structure (with the missing subitems) makes it really difficult to navigate and understand the structure of the content on a page:

https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Select.html#properties-rendertype-selectcheckbox

In the TCAref a lot of information was combined into one page (compared to how it was before, where the information existed on subpages with less content). Now we have for example, for the type _select_ with several _renderTypes_ with different options for this type.

The missing menu items make it

* more difficult to understand the structure on the page (and the structure of the TCA options)
* difficult to jump directly to a specific renderType or option

**Comment by DanielSiepmann** [comment]
Thanks for your thoughts and reports. We've heard your pain and try to improve.

**Comment by sypets** [comment]
I have seen several other docs projects lately, who add an additional table of contents in the right column, e.g. https://developers.google.com/web/tools/chrome-devtools/evaluate-performance

This has the main menu on the left. The right columns add a table of contents for the subsections on the current page. 

Another alternative is of course (what we are also using in some places) to add a table of contents at the beginning of a page. Symfony docs does it that way, at least on some pages: https://symfony.com/doc/current/setup.html

I think it is important to solve this in general and try to do it consistently in the .rst files as well.

Related is also the question of how you structure the content (e.g. all-on-one pages, toctree-only pages and content on subpages, etc.), see https://github.com/TYPO3-Documentation/T3DocTeam/issues/147

**Comment by DanielSiepmann** [comment]
I've talked to Benjamin, and the answer why only 2 levels are rendered is: We wanna have an expected behaviour. Those two levels are always documents, no content within documents.

I would like to keep that. Nevertheless we will try to add a table of content in addition.
Benjamin gave me some sources to find solutions:
* https://github.com/TYPO3-Documentation/sphinx_typo3_theme/blob/master/sphinx_typo3_theme/layout.html#L158-L163 (Current part which generates our navigation.
* https://github.com/f5devcentral/f5-sphinx-theme Another theme which has a separate table of content beside: https://github.com/f5devcentral/f5-sphinx-theme/blob/194443630c4f2ae7f2eaa8a00a8f57fbfe292264/f5_sphinx_theme/layout.html#L79-L86
* https://github.com/topics/sphinx-theme General list of themes for inspiration

**Comment by marble** [comment]
FYI: https://sphinx-themes.org/

Technically it is jus a `{{ toc }}` marker in the templates to obtain a table of contents for the page. But what's a nice solution for everybody and every device? One - easy - way to start could be to add that TOC in the left menu column as a separate list structure above or below the normal menu that's pointing to files.
Could be a start and still be improved.

**Comment by marble** [comment]
Oh boy, I just tried it, and this seems so easy to to:
![image](https://user-images.githubusercontent.com/307057/81049747-16c30a00-8ebf-11ea-90d5-68a6c2457f32.png)

I'll give this a real try very soon.

**Comment by marble** [comment]
Solved with theme version v4.2.1.

Example:

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Functions/Stdwrap.html

![image](https://user-images.githubusercontent.com/307057/88183794-33571e80-cc32-11ea-896f-b82d70bd68f1.png)
