### ISSUE TITLE
Scrollbar very thin and hard to use [MacOS]

### ISSUE THREAD

**Issue by TheNaderio** [TYPO3-Documentation/sphinx_typo3_theme#63]
At least on MacOS it can be very hard to use the scrollbar via click.
On MacOS the window-resizer is triggered instead.

A comment by @benjaminkott in Slack was:
> seems to be a bug, introduced by our third party consent management, [...]

![image](https://user-images.githubusercontent.com/25088164/76739185-27cb8680-676c-11ea-8e65-4a0ef66b29df.png)

**Comment by benjaminkott** [comment]
We added a hotfix, should now be more usable.
Thx for reporting 💖
