### ISSUE TITLE
Scaled image looks oddly distorted (aspect-ratio)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#64]
https://docs.typo3.org/m/typo3/tutorial-getting-started/9.5/en-us/ListModule/MassEditing/Index.html#edit-selected-fields-of-selected-records

```
.. figure:: ../../Images/BackendListSelectiveEditing.png
   :alt: Selecting records for editing
   :class: with-shadow
   :scale: 70
```

Though I probably wouldn't recommend using scale, I think this used to be ok, meaning the aspect-ratio was kept when scaling. 

This is the image: https://docs.typo3.org/m/typo3/tutorial-getting-started/9.5/en-us/_images/BackendListSelectiveEditing.png

**Comment by marble** [comment]
Thanks for reporting.

**Comment by marble** [comment]
Solution: Don't use the `:scale:` option in the Sphinx directive. It creates something like `<img alt="Selecting records for editing" class="with-shadow" src="../../_images/BackendListSelectiveEditing.png" style="width: 1276.1px; height: 856.8px;">` where this style interferes with the theme. The theme already takes care and makes it work properly:
![grafik](https://user-images.githubusercontent.com/307057/100471064-c8cf5700-30d9-11eb-8d71-fbbfd0668563.png)
