### ISSUE TITLE
Text from current events shown in Google snippets. 

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#66]
We now have the text of the events shown at the top of the docs pages in many snippets displayed on google:

![google](https://user-images.githubusercontent.com/13206455/77415414-bff7ea00-6dc2-11ea-8d70-1f1c121fcf54.png)

https://www.google.com/search?q=typoscript+exception+handler+debug&oq=typoscript+exception+handler+debug&aqs=chrome..69i57j33.7835j0j7&client=ubuntu&sourceid=chrome&ie=UTF-8

> TYPO3 Developer Days 2020. Akademie Hotel, Karlsruhe July 30th - August 2nd 2020. TYPO3 Explained. Release: master. Loading data. Menu. Quick Links.

We probably don't want that. 

Not sure how to solve this currently but there are some resources:

* https://www.hochmanconsultants.com/how-to-block-part-of-a-page-from-being-indexed-by-google-or-other-search-engines/
*  https://webmasters.stackexchange.com/questions/31994/how-to-tell-google-to-crawl-distinct-part-of-the-webpage
* etc.

**Comment by marble** [comment]
I had a look at what is written about this. There seems to be nothing that this theme can do about it. So I'd like to close the issue for now. The theme only provides a placeholder that may or may not be used by typo3.com. "They" would be the ones that should deal with this.
