### ISSUE TITLE
Styling of links as "buttons" - should only be used for actions? (see also typo3.org)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#7]
This is a question of usability and consistent markup / styling.

AFAIK, links that **cause an action** can be styled as buttons (and use appropriate markup), other links should not use this style, https://uxmovement.com/buttons/when-to-use-a-button-or-link/

Buttons are often used on GitHub or Gitlab. Not only do they give the hint that it is not just a link but an action is involved, they are also clearly visible and more prominent than the other links.

![submit](https://user-images.githubusercontent.com/13206455/72076749-58b7b700-32f6-11ea-9d74-c222e74fdd57.png)

On docs.typo3.org we have 3 different use cases:

1. normal links
2. "button" links that link to an action, e.g. "Edit me on GitHub"
3. "fat" links: links that should be displayed more prominent and that will stand out if there are several links on one page. 

But we currently only have 2 choices in reST to choose from:

* normal links
* the rst-class:: horizbutton 

`.. rst-class:: horizbuttons-primary-xxl`

generated HTML: 
```
<ul class="horizbuttons-primary-xxl simple">
<li><a class="reference internal" href="About.html#how-to-read-this-guide"><span class="std std-ref">How to Read This Guide</span></a></li>
</ul>
```

Currently, we often use the horizbutton for some links that should be prominent, e.g. quicklinks, for example see startpage docs.typo3.org. But they are not actions.

![quicklinks](https://user-images.githubusercontent.com/13206455/72076250-89e3b780-32f5-11ea-9aba-176b7d39295c.png)

Whether these look like buttons or just have box around them - up for debate.
I think, they look like buttons and it may not be the best choice.

Maybe a better choice is to put several links in a box. 

This is a question of how to style this, what our options are with .rst formatting and what are our best practices for the manuals.

See also, typo3.org, it is similar (but they these look a little less like buttons because they don't have rounded edges:

https://typo3.org/community/teams/typo3-development

![dash](https://user-images.githubusercontent.com/13206455/72076635-1e4e1a00-32f6-11ea-848f-d2e53aed7133.png)

**Comment by marble** [comment]
I don't see any problem with the way we are using our "list items as buttons".
Besides that, this issue is more a memo or a request for comments. It is not directly a real issue with the theme. As I am trying to get rid of actual tickets here I'm closing this now. If somebody has a real problem with this and has a better solution: Feel free to come back with a new ticket for this.
