### ISSUE TITLE
Using hierarchical lists may lead to "quote" style

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#73]
![indent-problem](https://user-images.githubusercontent.com/13206455/79301715-8bbba900-7eea-11ea-89e7-8a6897708aa4.png)

source:

```
#. **Module configuration**: The following options are available:

   * ``access``: can contain several, separated by comma

      * ``admin``: the module is accessible to admins only
      * ``user``: the module can be made accessible per user
      * ``group``: the module can be made accessible per usergroup

   * Module ``icon``
```

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/BackendModules/BackendModuleApi/Index.html#registering-new-modules

**Comment by marble** [comment]
No, everything is working as expected. Note that there is an extra blank at the beginning of the nested list. It's kind of an optical illusion becaus it's difficulat to align with the above 
```
``
 * second list
```
I fixed it with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/9ba599642a116d1867624805be59b2f051bdc0b5

**Comment by sypets** [comment]
The list on the second level must be indented with exactly 2 spaces?

Would just like to avoid this error in the future.

**Comment by marble** [comment]
It is two because you have two columns at the beginning of the outer list:
![image](https://user-images.githubusercontent.com/307057/79340736-0f958580-7f2b-11ea-954d-96e78e18f439.png)

But afterwards there are three:
![image](https://user-images.githubusercontent.com/307057/79340900-3ce23380-7f2b-11ea-9fb1-b4839e3421f1.png)

The extra one indentation creates the blockquote. 

In fact, I often use this form:
```
12345678901234567890
                  1                  2
•  Here is the item of a list with 'bullet, blank, blank' at the beginning.
   Afterwards I can use 'tab' to jump to the correct continuation because
   the tab setting in my editor is 3.

   * ``admin``: the module is accessible to admins only
   * ``user``: the module can be made accessible per user
   * ``group``: the module can be made accessible per usergroup
```
