### ISSUE TITLE
Color scheme (orange) of docs.typo3.org inconsistent with TYPO3 style guide

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#79]
**Summary**: 

* https://docs.typo3.org, https://typo3.com and some logos use "dark" TYPO3 orange: #ff8700
* ![#ff8700](https://placehold.it/15/ff8700/000000?text=+) `#ff8700`

* https://typo3.org and [styleguide](https://typo3.org/fileadmin/t3o_common_storage/images/styleguide/TYPO3_Printstyleguide_2018-02-23.pdf) use "lighter" TYPO3 orange: #f49700
- ![#f49700](https://placehold.it/15/f49700/000000?text=+) `#f49700`

AFAIK the lighter one (from styleguide) should be used everywhere, so we should change this.

(I have not checked other colors, only orange)

---------

I created new images from some of the [icons that was prepared by the design team](https://github.com/TYPO3-Documentation/images/blob/master/design-team/icons_preview/Images.rst) and noticed that the "TYPO3" orange shades from the style guide clash with the orange we use on docs.typo3.org for "Edit me on GitHub", "Area for home in top left" and  the "orange buttons".

These use the color rgb(255, 135, 0), #ff8700.

The orange colors from [Style Guide](https://typo3.org/fileadmin/t3o_common_storage/images/styleguide/TYPO3_Printstyleguide_2018-02-23.pdf) are:

```
key color
CMYK: 0/47/100/0
RGB: 244/151/0
Hex: f49700

stage orange dark
CMYK: 0/47/100/10
RGB: 225/141/0
Hex: e18d00

stage orange light
CMYK: 0/40/85/0
RGB: 247/168/49
Hex: f7a831
```

The icons from the design team (e.g. arrow) use the key color. 

This is how it looks: 

https://docs.typo3.org/Tips/UsingThisSite/Index.html

![mobilemenu](https://user-images.githubusercontent.com/13206455/54752610-0f6b6f00-4bdf-11e9-979a-147e67443a99.png)

**Comment by marble** [comment]
IMHO a single color for image annotation will not satify all needs. Instead we are probably more looking for a palette of recommended colors from which to choose in a given order until the one is found that fits the content of the image best.

I'd recommend to stay away from these colors as far as possible as they are making up the theme:
![image](https://user-images.githubusercontent.com/307057/85702665-ec334780-b6de-11ea-9b3d-a23b7e72ea9d.png)

Instead I can very well imagine that 'code-colors' could work:
![image](https://user-images.githubusercontent.com/307057/85702861-1be24f80-b6df-11ea-84be-46b749598ba4.png)

Btw, this is a very convenient color picker: http://hslpicker.com/#07f

![image](https://user-images.githubusercontent.com/307057/85703176-649a0880-b6df-11ea-87ea-0156e3876737.png)


180 degrees ahead at the opposite side of the color circle we can find a contrasting color: 
![image](https://user-images.githubusercontent.com/307057/85703457-aa56d100-b6df-11ea-8771-ac898072c6eb.png)

I would go for this contrasting color to start with. Once that isn't enough we could choose another one.

**Comment by marble** [comment]
Considered obsolete since we have theme sphinx_typo3_theme

**Comment by sypets** [comment]
The different oranges used throughout the TYPO3 websites are still an issue. 

1) darker orange, used on docs.typo3.org, typo3.com etc.
* e.g. "Edit on GitHub" docs.typo3.org: border-color: #ff8700;
* e.g. "Download TYPO3" on get.typo3.org #ff8700;
* ![#ff8700](https://placehold.it/15/ff8700/000000?text=+) `#ff8700`

2) lighter orange, used on typo3.org and in content style guide
* e.g. TYPO3 content style guide: #f49700, #e18d00, #f7a831
- ![#f49700](https://placehold.it/15/f49700/000000?text=+) `#f49700`

These colors are not just different, they clash. I still don't know why different oranges are being used and why this was changed. But it is not a specific problem of docs, it is a general problem.

It seems like everyone is using the darker colors except for typo3.org and the content style guide, so effectively the content style guide is being ignored.

Please correct me, if I am wrong and let me finally understand what is happening here.

**Comment by marble** [comment]
I'm closing this issue because I don't consider it important in any practical way.
