### ISSUE TITLE
Absolute width results in fragmented texts

### ISSUE THREAD

**Issue by legomaennchen** [TYPO3-Documentation/sphinx_typo3_theme#80]
I'll never understand the bad habit of fixing the width of main content. There is no need for big empty and useless spaces on screen.
With Typo3's new design, many texts are weird fragmented and get lost by cutting off. 

E.g. here: 
https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/Typo3CoreEngine/Database/Index.html

There are many Typo3 sites like this. The text in the boxes in the middle ist not readable unless I clear manually this CSS line: 

.page-main-inner {
...
    width: 1140px;
...
}

Many, many textboxes would be read easier without that absolute width - e.g. lines of code - the need to scroll horizontal to see the whole codeline is really really annoying.

**Comment by marble** [comment]
I totally agree. But others were strongly in favor of a max-width. To give both sides what they want in an unobstructive way I'm planning to add:
![grafik](https://user-images.githubusercontent.com/307057/100113320-7b9c7c80-2e70-11eb-98c6-6b1e1bcab2fd.png)

Effect will be, that once you make the width of your browser window ≥1800 pixels the limit will disappear and all of your window is used.

**Comment by marble** [comment]
Solved with theme v4.3 (and container v2.7)
