### ISSUE TITLE
Rendering of indented text as quotes - a lot of docs pages now look "broken"

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#81]
For a while (since relaunch of new theme), indented text is rendered as quotes. It looks like this:

![quote](https://user-images.githubusercontent.com/13206455/87812971-51eb9d00-c861-11ea-8925-3f8d311e62ed.png)

I've already fixed a few of these. But they are everywhere. Also in older docs which we really do not maintain that much anymore.

Since we rarely or maybe never ever use quotes or something that should be rendered as such, can we do away with this?

**Comment by marble** [comment]
No, for the reasons of this thread. https://app.slack.com/client/T024TUMLZ/C028JEPJL/thread/C028JEPJL-1603790611.135100
