### ISSUE TITLE
Images are sometimes not clearly recognizable and do not stand out enough from the text.

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#83]
Images are not clearly recognizable and do not stand out enough from the text - this is often the case, if the image contains text itself.

This impairs the readability on the page. It makes reading and skimming (quickly scrolling and glancing over a page to find relevant content) through a page more difficult.

## Examples:

1. [Editors's Tutorial > Page Properties](https://docs.typo3.org/m/typo3/tutorial-editors/10.4/en-us/Pages/PageProperties/Index.html)

![images2](https://user-images.githubusercontent.com/13206455/89115787-8465de80-d48c-11ea-81a2-afdb8a8e726c.png)

Most pages look more ok to me, for example this one https://docs.typo3.org/m/typo3/tutorial-editors/10.4/en-us/AccessControl/Login/Index.html, especially if there are not too many images or the image has a different background color or there is some dividing element (e.g. a note)

## Possible solutions

* indent images
* add margin around images (just a little more would probably already suffice)
* add shadow, frame, etc. around images

I don't know what the best solution would be. We have lots of images with text.

**Comment by marble** [comment]
We can optionally use `:class: with-border with-shadow`. That's all we want to do about this right now. Work is taking place somewhere else to unify the colors and icons of annotations within the images.
