### ISSUE TITLE
Handle Plantuml and Graphviz images

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/sphinx_typo3_theme#86]
Maybe 'object' needs tweaking like so:
<pre>
.rst-content .plantuml > object {
    max-width: 100%;
    height: auto !important;
}
</pre>

**Comment by alexander-nitsche** [comment]
This style would be good to have in the current theme release in order to fit diagrams into the page properly.

**Comment by marble** [comment]
Done with
* e67d144 Use max-width:100% for PlantUML objects
