### ISSUE TITLE
Consider light color scheme for code snippets

### ISSUE THREAD

**Issue by mbrodala** [TYPO3-Documentation/sphinx_typo3_theme#88]
The code snippets throughout the docs are currently rendered with a dark color scheme:

![image](https://user-images.githubusercontent.com/5037116/96259220-96e8b200-0fbd-11eb-8fda-504472716ad0.png)

This can make [sections with many snippets and little text](https://docs.typo3.org/m/typo3/guide-frontendlocalization/master/en-us/LocalizedContent/Index.html#connected-content) rather crowded given that the dark blocks are rather heavy.

Also some studies suggest that light color schemes are superior to dark color schemes for readability and speed of recognition:

https://stitcher.io/blog/why-light-themes-are-better-according-to-science

Thus we should consider and discuss whether it makes sense to switch to a light color scheme instead.

**Comment by sypets** [comment]
See also older issue: t3SphinxThemeRtd#122 (that was the "old" theme, theme is now in different repo) and PR t3SphinxThemeRtd#140.

I think the readability of the snippets was already improved with these changes (Benjamin Kott). 

I think this is a good suggestion. But there will be people with very strong opinions about both ways.

**Comment by flicstar** [comment]
I wanted to read those older issues but I couldn't find them when I search across the Org. 
In any case, my two cents is that we just ensure we get the contrast right for accessibility. 
If light vs dark is a polarizing issue, perhaps we could run a poll across the community to decide? Make it fun? 
I will ask the WriteTheDocs community to see what the general view on this is.

**Comment by marble** [comment]
### Yes, too dark
I too think the background of code examples is too dark. But before we do any quick changes let's thoroughly think this through and let's make sure we take all relevant aspects into account. And then let's have some tests first. I suggest we start a list with things to be considered:

### To be considered

- Accessibility
- Eye friendlyness - for health reasons [1]
- Meanwhile we are using cookies on docs.typo3.org. So a Javascript solution is possible to let people customize appearance in some ways preconfigured way.
- People may want to use  "Darkreader". That is a popular browser extension for Firefox and Chrome. It shows most "bright" websites in a nice looking dark mode. It should be possible to make our theme compatible with easy use of Darkreader. 

### Tip: Stylebot
Checkout Chrome browser addon "Stylebot". It lets you overwrite css style and, if activated, it can apply those changes to everything you read on docs.typo3.org. Unless you disable your custom style.

### Health
[1] Meanwhile eye friendliness is something I depend on. The white of a screen isn't just a reflection of light on a surface. It's actually a bright shining light source. And staring into that light can actually hurt your eyes. I'm making that experience. So for me it's not a matter of taste but something mandatory, to not have to stare into a shining light.

**Comment by sypets** [comment]
I think the reference @mbrodala linked to made several good points: https://stitcher.io/blog/why-light-themes-are-better-according-to-science

e.g. 

> Often when I share these arguments with someone who clings to the dark side, they tell me light colour schemes hurt their eyes because they are too bright; you might be thinking the same right now. I've got two answers for you.

> **First**: you don't need to use a white #fff background with black #000 text. There's lots of light colour schemes that don't go to the extreme ends. The important thing is that there's enough contrast between fore- and background, and that the background is lighter than the foreground. **Second**: you can always adjust the brightness of your screen. You don't need to turn it up to a 100%! You'd only do that if the text is otherwise unreadable, and guess when that happens? If you'd use a dark scheme!

**Comment by susannemoog** [comment]
From @mbrodala's link and @marble's arguments, we could come up with a combined solution that uses a light(er) theme by default but allows the user to switch to other themes.

**Comment by marble** [comment]
https://docs.typo3.org/m/typo3/demo-t3SphinxThemeRtd/master/en-us/ImagesAndFigures/Index.html#bright-images-with-border-and-shadow

To me the current selection of values for border and shadow looks rather nice:

![image](https://user-images.githubusercontent.com/307057/96334277-cc4dd800-106f-11eb-81a8-f29be2074e9a.png)

**Comment by marble** [comment]
Here's another version found in the internet(at https://miguendes.me/how-to-use-fixtures-as-arguments-in-pytestmarkparametrize):

![grafik](https://user-images.githubusercontent.com/307057/99886677-c767df80-2c3e-11eb-96c2-9a47fe86225d.png)

**Comment by sypets** [comment]
Suggestion to join forces with accessibility team and to unify how code snippets are displayed (see also TypoScript editing  in TYPO3 backend).

Apart from that, I don't think there is urgency for this, only _if_ this is addressed again, I think it makes sense to join forces and combine efforts.

Already mentioned in also comment in other issue: https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/178#issuecomment-1445299650

**Comment by marble** [comment]
Solved with https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/178#issuecomment-1445311861
