### ISSUE TITLE
[FEATURE] html/css Bootstrap 4 component "Cards with tabs" (Registerkarten) wanted

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/sphinx_typo3_theme#89]
Slack has a nice looking component on their site:
https://slack.com/intl/de-de/help/articles/360025446073-Leitfaden-f%C3%BCr-mobile-Benachrichtigungen#android-1

![grafik](https://user-images.githubusercontent.com/307057/99062910-ff6a8500-25a3-11eb-8344-922170dd8f5e.png)

Who can help creating the html+css for such a component for our sphinx_typo3_theme?

**Comment by simonschaufi** [comment]
I guess this could be a starting point: https://getbootstrap.com/docs/4.5/components/card/#navigation

**Comment by marble** [comment]
> I guess this could be a starting point: https://getbootstrap.com/docs/4.5/components/card/#navigation

Sure, I know ;-)

**Comment by marble** [comment]
Done with v4.4 and Sphinx extension sphinxcontrib-tabs

**Comment by simonschaufi** [comment]
see https://github.com/TYPO3-Documentation/sphinx_typo3_theme/commit/daf621127805642532f5c8433a7d71c0ebb68390
