### ISSUE TITLE
Add license text to footer

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/sphinx_typo3_theme#9]
Property for license text could be added to Settings.cfg and license added to footer (like copyright and authors). That way, it is not necessary to put it on the start page (though that would of course still be possible). 

Related:

* https://github.com/TYPO3-Documentation/T3DocTeam/issues/89

**Comment by marble** [comment]
IMHO it is perfectly ok to just have that license note on the start page of a manual. From somebody who is thinking about reusing content I can expect that he has a look at the first page.
And to put something like to the footer doesn't look like a smart solution to me:
![grafik](https://user-images.githubusercontent.com/307057/100469884-69704780-30d7-11eb-9f22-f9c521504181.png)
